FROM java:8
COPY docker/SchedulingActors-Akka-assembly-1.0.jar SchedulingActors-Akka-assembly-1.0.jar
RUN java -cp SchedulingActors-Akka-assembly-1.0.jar com.github.janikibichi.learnakka.schedulingActors.LoggingWithActors
